### ISSUE TITLE
你好， 请问为什么显示没有itunes手机备份。

### ISSUE THREAD

**Issue by acxiao004** [wongjohn/wechat-analyser#1]
已经备份了itunes备份。但是打开软件显示没有发现itunes手机备份

**Comment by wongjohn** [comment]
@acxiao004  你好，我前几个月也发现相同的问题了。

这是因为Mac系统下的Rootless机制导致的——在Rootless机制下，即使你在root权限下，也不能随心所欲的读写所有路径——而“iTunes备份存储目录”（Library/Application Support/MobileSync/Backup），刚好变成了这样的目录。

我目前的解决办法——关闭Rootless（如果有其他解决办法，欢迎跟帖）：
1. 重启按住 Command+R，进入恢复模式，打开Terminal。 
2. 键入命令 csrutil disable 
3. reboot 
如果重新打开，用同样的方法输入csrutil enable。

**Comment by AnLuoRidge** [comment]
手动把系统中的备份复制到一个可读写的目录，再改app的默认路径行不行？
https://github.com/wongjohn/wechat-analyser/blob/9278d840d05717981b2bd37ec813c8970fcbfc4a/src/renderer/constants/index.js#L3

**Comment by wongjohn** [comment]
我自己还没有试过，你尽可以自己试试。


| |
王士江
|
|
shijiangjiayou@163.com
|
签名由网易邮箱大师定制


在2019年09月27日 10:18，Alan Ridge<notifications@github.com> 写道：

手动把系统中的备份复制到一个可读写的目录，再改app的默认路径行不行？
https://github.com/wongjohn/wechat-analyser/blob/9278d840d05717981b2bd37ec813c8970fcbfc4a/src/renderer/constants/index.js#L3

**Comment by AnLuoRidge** [comment]
试了下，可行的。

**Comment by change2hao** [comment]
> @acxiao004 你好，我前几个月也发现相同的问题了。
> 
> 这是因为Mac系统下的Rootless机制导致的——在Rootless机制下，即使你在root权限下，也不能随心所欲的读写所有路径——而“iTunes备份存储目录”（Library/Application Support/MobileSync/Backup），刚好变成了这样的目录。
> 
> 我目前的解决办法——关闭Rootless（如果有其他解决办法，欢迎跟帖）：
> 
> 1. 重启按住 Command+R，进入恢复模式，打开Terminal。
> 2. 键入命令 csrutil disable
> 3. reboot
>    如果重新打开，用同样的方法输入csrutil enable。

MacOS 10.15 按照这种方式设置后还是提示 “没有发现iTunes手机备份 ”

**Comment by change2hao** [comment]
> 试了下，可行的。

能否把具体步骤命令说明一下，感谢
